name: campkeeper_riverpod
description: "A flutter app for listing the campsites, you can cluster them on the map also, or see their details. the state management system is Riverpod."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.3.4
  geolocator: ^10.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  
  mockito: ^5.4.4

flutter:
  uses-material-design: true